#PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: timetablr_api_development
  username: <%= ENV['TIMETABLR_API_DB_USERNAME'] %>
  password: <%= ENV['TIMETABLR_API_DB_PASSWORD'] %>
  host: localhost
  port: 5432
test:
  <<: *default
  database: timetablr_api_test
  username: <%= ENV['TIMETABLR_API_DB_USERNAME'] %>
  password: <%= ENV['TIMETABLR_API_DB_PASSWORD'] %>
production:
  <<: *default
  database: timetablr_api_production
  username: timetablr_api
  password: <%= ENV['TIMETABLR_API_DATABASE_PASSWORD'] %>